### ISSUE TITLE
Deco IDE

### ISSUE THREAD

**Issue by Eioxin** [Eioxin/drinkup#7]
Hey,
wenn du heute Zeit hast kannst du dir mal https://www.decoide.org/ anschauen ob wir das für Android nutzen können.

**Comment by NUlsamer** [comment]
https://www.decoide.org/docs/projects
Beim Erstellen von nem Projekt werden sowohl Ordner für Android als auch für iOS erstellt.
"To make your project permanent, use File > Save Project and choose a directory. At this point, the project will be moved out of /tmp and be saved permanently.

Your new project will have the following files and directories:
android/ - The files necessary to open your project in Android Studio and build for Android.
ios/ - The files necessary to open your project in Xcode and build for iOS."

Also ja, können wir auch für Android nutzen.

**Comment by Eioxin** [comment]
Mir geht es vor allem darum, ob ich das Tool mit dem ich per Clicks meinen Code bauen kann, verwenden zu können. 
Weil Downloads sind nur für ios möglich.

**Comment by NUlsamer** [comment]
Hm so wie ich das seh geht das auch nur indem du über VirutalBox nen mac OS aufsetzt und darüber Xcode installierst... aber wir müssen ja sowieso über virtualbox mac os aufsetzen, um die iOS App zu programmieren...
https://blog.udemy.com/xcode-on-windows/

Wenn du dann Xcode hast kannste dich ja an die anleitung von deco IDE halten.

**Comment by Eioxin** [comment]
Stimmt
